name: Update README

on:
  push:
    branches:
      - main   

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update README.md
        run: |
          python src/update_readme.py

      - name: Commit and push if changed
        run: |
          git config --global user.email ${{ secrets.USER_EMAIL }}  
          git config --global user.name ${{ secrets.USER_NAME }}  
          git add README.md
          git commit -m "Automatically update README.md" || exit 0
          git push
